// AUTO-GENERATED by scripts/manifest-to-fork.mjs - lists every fork bundle.
import type { Fork } from '../src/types.js';
import fork0 from './atomic-habits/fork.js';
import fork1 from './counting-sheep/fork.js';
import fork2 from './failing-forward/fork.js';
import fork3 from './how-to-win-friends-and-influence-people/fork.js';
import fork4 from './ostrava-guide/fork.js';
import fork5 from './psychology-of-money/fork.js';
import fork6 from './the-48-laws-of-power/fork.js';
import fork7 from './the-daily-stoic/fork.js';
import fork8 from './thinking-fast-and-slow/fork.js';

export const FORKS: Record<string, Fork> = {};
for (const f of [fork0, fork1, fork2, fork3, fork4, fork5, fork6, fork7, fork8]) FORKS[f.meta.id] = f;
