#!/usr/bin/env node
// Convert legacy JSON manifest(s) into typed TS fork files under forks/.
//
// Usage:
//   node scripts/manifest-to-fork.mjs                 # convert every manifests/*.json
//   node scripts/manifest-to-fork.mjs manifests/x.json
//
// Static feeds (cards in the manifest) become forks/<forkId>/<feedId>.ts
// (StaticFeed), sitting next to fork.ts. Manifests containing a generator-backed
// feed are skipped: those are hand-written as `<feed-id>.dynamic.ts`. After
// conversion the registry forks/index.ts is regenerated by scanning every
// forks/<dir>/fork.ts.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FORKS_DIR = join(ROOT, 'forks');
const MANIFESTS_DIR = join(ROOT, 'manifests');

function manifestFiles() {
  const args = process.argv.slice(2);
  if (args.length) return args.map((a) => (a.startsWith('/') ? a : join(ROOT, a)));
  return readdirSync(MANIFESTS_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => join(MANIFESTS_DIR, f));
}

// Ids become file/folder names and TS import paths, so they must be safe kebab-case
// and not collide with reserved files (fork.ts, index.ts) or the .dynamic suffix.
const RESERVED_IDS = new Set(['fork', 'index']);
function assertSafeId(id, kind) {
  if (typeof id !== 'string' || !/^[a-z0-9-]+$/.test(id)) {
    throw new Error(`Invalid ${kind} id ${JSON.stringify(id)}: must match /^[a-z0-9-]+$/`);
  }
  if (RESERVED_IDS.has(id) || id.endsWith('.dynamic')) {
    throw new Error(`Reserved ${kind} id ${JSON.stringify(id)}: cannot be "fork", "index", or end with ".dynamic"`);
  }
}

function feedFileSource(feed, cards) {
  const meta = {
    id: feed._id || feed.id,
    title: feed.title || '',
    description: feed.description || '',
    imageSrc: feed.imageSrc || '',
    mode: feed.mode || 'sequential',
    scrollDirection: feed.scrollDirection || 'vertical',
    engagement: feed.engagement === true,
  };
  const cardObjs = cards.map((c) => ({ id: c._id || c.id, variants: c.variants || [] }));
  const body = {
    ...meta,
    cards: cardObjs,
  };
  return `import type { StaticFeed } from '../../src/types.js';\n\n` +
    `const feed: StaticFeed = ${JSON.stringify(body, null, 2)};\n\n` +
    `export default feed;\n`;
}

function forkFileSource(fork, feedIds) {
  const imports = feedIds
    .map((id, i) => `import feed${i} from './${id}.js';`)
    .join('\n');
  const meta = { id: fork._id || fork.id, title: fork.title || '', description: fork.description || '', imageSrc: fork.imageSrc || '' };
  if (fork.actionLabel) meta.actionLabel = fork.actionLabel;
  if (fork.actionUrl) meta.actionUrl = fork.actionUrl;
  const feedList = feedIds.map((_, i) => `feed${i}`).join(', ');
  return `import type { Fork } from '../../src/types.js';\n${imports}\n\n` +
    `const fork: Fork = {\n  meta: ${JSON.stringify(meta, null, 2).replace(/\n/g, '\n  ')},\n  feeds: [${feedList}],\n};\n\n` +
    `export default fork;\n`;
}

function convertManifest(path) {
  const manifest = JSON.parse(readFileSync(path, 'utf8'));
  const feeds = manifest.feeds || [];
  const forks = manifest.forks || [];
  const cards = manifest.cards || [];

  if (feeds.some((f) => f.generatorId)) {
    console.log(`- skip ${basename(path)} (generator-backed; hand-written as .dynamic.ts)`);
    return;
  }

  const feedById = new Map(feeds.map((f) => [f._id || f.id, f]));
  const cardsByFeed = new Map();
  for (const card of cards) {
    const fid = card.feedId;
    if (!cardsByFeed.has(fid)) cardsByFeed.set(fid, []);
    cardsByFeed.get(fid).push(card);
  }
  for (const list of cardsByFeed.values()) list.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  for (const fork of forks) {
    const forkId = fork._id || fork.id;
    assertSafeId(forkId, 'fork');
    const dir = join(FORKS_DIR, forkId);
    mkdirSync(dir, { recursive: true });

    const feedIds = (fork.feedIds || []).filter((id) => feedById.has(id));
    for (const feedId of feedIds) {
      assertSafeId(feedId, 'feed');
      const feed = feedById.get(feedId);
      const feedCards = cardsByFeed.get(feedId) || [];
      writeFileSync(join(dir, `${feedId}.ts`), feedFileSource(feed, feedCards));
    }
    writeFileSync(join(dir, 'fork.ts'), forkFileSource(fork, feedIds));
    console.log(`- ${forkId}: ${feedIds.length} feeds, ${feedIds.reduce((n, id) => n + (cardsByFeed.get(id)?.length || 0), 0)} cards`);
  }
}

function regenerateRegistry() {
  const dirs = readdirSync(FORKS_DIR)
    .filter((d) => statSync(join(FORKS_DIR, d)).isDirectory() && existsSync(join(FORKS_DIR, d, 'fork.ts')))
    .sort();
  const imports = dirs.map((d, i) => `import fork${i} from './${d}/fork.js';`).join('\n');
  const list = dirs.map((_, i) => `fork${i}`).join(', ');
  const src = `// AUTO-GENERATED by scripts/manifest-to-fork.mjs - lists every fork bundle.\n` +
    `import type { Fork } from '../src/types.js';\n${imports}\n\n` +
    `export const FORKS: Record<string, Fork> = {};\n` +
    `for (const f of [${list}]) FORKS[f.meta.id] = f;\n`;
  writeFileSync(join(FORKS_DIR, 'index.ts'), src);
  console.log(`\nRegistry: ${dirs.length} forks -> forks/index.ts`);
}

for (const path of manifestFiles()) convertManifest(path);
regenerateRegistry();
